language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 2.0.0
      mono: none
      env: CONFIGURATION=Debug DOTNETCORE=1
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 2.0.0
      mono: none
      env: CONFIGURATION=Release DOTNETCORE=1

script:
  - dotnet restore
  - cd src/PhotoStats
  - dotnet build -c $CONFIGURATION
